export function managementHtml(csrf: string): string {
  return `<!doctype html><html lang="zh-Hant"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="csrf-token" content="${csrf}"><title>bookmarkdown · mcp-server</title><link rel="stylesheet" href="/assets/style.css"><script src="/assets/app.js" defer></script></head><body>
<main><header><div class="eyebrow">LOCAL CONTROL / MCP</div><h1>bookmarkdown<span>mcp-server</span></h1><p>一個 server，連接你的 agents 與多台裝置。</p><div class="badge" id="status">連線中…</div></header>
<p id="notice" role="status" aria-live="polite"></p>
<section><div class="section-head"><h2>連線設定</h2><span>目前執行中的服務</span></div><div class="connections">
<article><h3>Agent · MCP HTTP</h3><label for="mcp-url">本機端點</label><div class="copy-row"><input id="mcp-url" readonly><button data-copy="mcp-url">複製</button></div><label for="mcp-token">Bearer token</label><div class="copy-row"><input id="mcp-token" type="password" value="••••••••••••••••" readonly><button data-reveal="mcpToken">顯示</button><button data-token-copy="mcpToken">複製</button></div><p class="hint">在 agent 的 MCP HTTP 設定加入 Authorization: Bearer &lt;token&gt;。</p></article>
<article><h3>套件 · WebSocket</h3><label for="ws-url">本機端點</label><div class="copy-row"><input id="ws-url" readonly><button data-copy="ws-url">複製</button></div><label for="bridge-token">配對 token</label><div class="copy-row"><input id="bridge-token" type="password" value="••••••••••••••••" readonly><button data-reveal="bridgeToken">顯示</button><button data-token-copy="bridgeToken">複製</button></div><p class="hint">在套件的 MCP 設定填入 WebSocket URL 與配對 token。</p></article>
</div><div id="lan-urls"></div></section>
<section><div class="section-head"><h2>支援套件與裝置</h2><button id="refresh">重新整理</button></div><p>BookMarkdown / BMD · Chrome · bridge protocol v2</p><p class="hint" id="mode"></p><div id="devices">尚未連接套件。</div></section>
<section><h2>伺服器設定</h2><p class="hint">設定儲存於本機，重新啟動 server 後生效。</p><form id="settings">
<label class="toggle"><input id="lanEnabled" type="checkbox">開啟區網連線（HTTP / WS）</label><p class="hint">其他裝置可透過區網 IP 配對。請在可信任的區網使用；管理頁僅限本機開啟。</p>
<div class="fields"><label>MCP port<input id="mcpPort" type="number" min="1" max="65535" required></label><label>WebSocket port<input id="webSocketPort" type="number" min="1" max="65535" required></label></div>
<details><summary>進階設定</summary><div class="fields"><label>請求逾時（ms）<input id="requestTimeoutMs" type="number" min="100" max="60000" required></label><label>套件連線上限<input id="maxConnections" type="number" min="1" max="64" required></label><label>同時請求上限<input id="maxPendingRequests" type="number" min="1" max="256" required></label></div><label>允許的 extension IDs（選填，以逗號分隔）<input id="extensionIds" placeholder="留空接受所有相容套件"></label><p class="hint" id="overrides"></p><p class="hint" id="environment-only"></p></details>
<button class="primary" type="submit">儲存設定</button></form><div class="rotate"><button data-rotate="mcpToken">重建 MCP token</button><button data-rotate="bridgeToken">重建配對 token</button><span class="hint">重啟後需更新對應裝置的 token。</span></div><p class="hint">設定檔：<code id="config-path"></code></p></section>
<footer>bookmarkdown · 本機管理 / Streamable HTTP</footer></main></body></html>`;
}
export const managementCss = `:root{color-scheme:dark;--bg:#101719;--panel:#182124;--line:#334044;--muted:#a7b6b9;--accent:#c6ef8d}*{box-sizing:border-box}body{margin:0;background:var(--bg);color:#edf2ee;font:15px/1.65 system-ui,-apple-system,sans-serif}main{max-width:1040px;margin:auto;padding:48px 28px}header{position:relative;margin-bottom:42px}.eyebrow{color:var(--accent);font-size:12px;letter-spacing:3px}h1{font-size:clamp(42px,7vw,76px);line-height:1.05;letter-spacing:-3px;margin:24px 0}h1 span{display:block;color:var(--accent)}header p{color:var(--muted)}.badge{display:inline-block;border:1px solid var(--line);border-radius:30px;padding:5px 14px;font-size:13px}section{border-top:1px solid var(--line);padding:26px 0}.section-head{display:flex;align-items:center;justify-content:space-between;gap:16px}.section-head span,.hint{color:var(--muted);font-size:13px}h2{font-size:21px;margin:0 0 18px}h3{font-size:16px;margin-top:0}.connections,.fields{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:20px}article{background:var(--panel);border:1px solid var(--line);border-radius:14px;padding:22px}label{display:block;font-size:13px;color:var(--muted);margin:12px 0 6px}input{width:100%;background:#101719;border:1px solid var(--line);border-radius:6px;color:#edf2ee;padding:10px;font:14px/1.4 ui-monospace,monospace}input:focus,button:focus-visible{outline:2px solid var(--accent);outline-offset:2px}input:disabled{opacity:.55}.copy-row{display:flex;gap:6px}.copy-row input{min-width:0}button{border:1px solid var(--line);border-radius:6px;background:var(--panel);color:#edf2ee;cursor:pointer;padding:9px 12px;white-space:nowrap}button:hover{border-color:var(--accent)}button:disabled{opacity:.5;cursor:default}.primary{background:var(--accent);color:#152013;margin-top:20px;border:0;font-weight:600}.toggle{font-size:15px;color:#edf2ee;display:flex;align-items:center;gap:10px}.toggle input{width:18px;height:18px;accent-color:var(--accent)}details{margin-top:18px}summary{cursor:pointer}.rotate{display:flex;flex-wrap:wrap;align-items:center;gap:10px;margin-top:24px}#notice:empty{display:none}#notice{border-left:3px solid var(--accent);padding:12px 16px;background:var(--panel)}.device{background:var(--panel);border-radius:8px;padding:14px;margin:8px 0;overflow-wrap:anywhere}.device span{display:block;font-size:13px;color:var(--muted)}code{overflow-wrap:anywhere}footer{color:var(--muted);font-size:12px;margin-top:24px}#lan-urls p{overflow-wrap:anywhere}@media(max-width:650px){main{padding:28px 18px}.connections,.fields{grid-template-columns:1fr}h1{letter-spacing:-2px}.copy-row button{padding:8px}.section-head span{display:none}}`;
export const managementJs = `const $=id=>document.getElementById(id);let state;const csrf=document.querySelector('meta[name="csrf-token"]').content;
const note=text=>$('notice').textContent=text;
async function api(path,body){const response=await fetch(path,{method:body?'POST':'GET',headers:body?{'Content-Type':'application/json','X-CSRF-Token':csrf}:{},body:body?JSON.stringify(body):undefined,cache:'no-store'});if(!response.ok){throw new Error((await response.json().catch(()=>({}))).error||'請求失敗，請確認 server 仍在執行。')}return response.json()}
async function copy(text){if(navigator.clipboard?.writeText){try{await navigator.clipboard.writeText(text);note('已複製。');return}catch{}}const field=document.createElement('textarea');field.value=text;document.body.append(field);field.select();const ok=document.execCommand('copy');field.remove();if(!ok)throw new Error('無法使用剪貼簿，請顯示後手動複製。');note('已複製。')}
function deviceList(devices){const list=$('devices');list.replaceChildren();if(!devices.length){list.textContent='尚未連接套件。裝好套件後，填入上方 URL 與配對 token。';return}for(const device of devices){const row=document.createElement('div');row.className='device';row.textContent=device.displayName+' · '+(device.status==='online'?'已連線':'離線');const detail=document.createElement('span');detail.textContent=device.extensionId+' / '+device.instanceId+' · '+device.operations.length+' 個操作';row.append(detail);list.append(row)}}
async function refresh(initial=false){state=await api('/api/status');$('status').textContent='服務運行中 · '+state.devices.filter(d=>d.status==='online').length+' 台裝置';$('mcp-url').value=state.mcpUrl;$('ws-url').value=state.webSocketUrl;$('mode').textContent=state.runtimeMode==='development'?'開發模式：任何符合協定、通過 token 驗證的 Chrome 套件皆可連線。':state.allowlistEnabled?'已啟用 extension ID 允許清單。':'不需預先登記 ID；接受符合協定並通過 token 驗證的 Chrome 套件。';deviceList(state.devices);$('lan-urls').replaceChildren();for(const endpoint of state.lanEndpoints){const p=document.createElement('p');p.textContent='區網 · '+endpoint.mcpUrl+' · '+endpoint.webSocketUrl;const button=document.createElement('button');button.textContent='複製端點';button.onclick=()=>copy(endpoint.mcpUrl+'\\n'+endpoint.webSocketUrl).catch(e=>note(e.message));p.append(' ',button);$('lan-urls').append(p)}if(state.restartRequired)note('設定已儲存。請在終端機重新啟動 server 後生效；上方端點及 token 仍是目前執行中的值。');if(initial){const extra=state.environmentOnly;$('environment-only').textContent='ENV 進階值 · WS host: '+extra.webSocketHost+' · TLS: '+(extra.webSocketTls?'開':'關')+' · payload: '+extra.maxPayloadBytes+' bytes · instances: '+extra.maxRegisteredInstances+' · hello timeout: '+extra.helloTimeoutMs+' ms';for(const [key,value] of Object.entries(state.settings)){if(!$(key))continue;if(key==='lanEnabled')$(key).checked=value;else $(key).value=Array.isArray(value)?value.join(', '):value;$(key).disabled=state.overrides.includes(key)}$('config-path').textContent=state.configPath;$('overrides').textContent=state.overrides.length?'由 ENV 覆寫：'+state.overrides.join(', '):'ENV 優先於設定檔。';for(const button of document.querySelectorAll('[data-rotate]'))button.disabled=state.overrides.includes(button.dataset.rotate)}}
document.addEventListener('click',async event=>{const button=event.target.closest('button');if(!button)return;try{if(button.dataset.copy)await copy($(button.dataset.copy).value);if(button.dataset.tokenCopy){const result=await api('/api/secrets',{which:button.dataset.tokenCopy});await copy(result.token)}if(button.dataset.reveal){const input=$(button.dataset.reveal==='mcpToken'?'mcp-token':'bridge-token');if(input.type==='text'){input.type='password';input.value='••••••••••••••••';button.textContent='顯示'}else{input.value=(await api('/api/secrets',{which:button.dataset.reveal})).token;input.type='text';button.textContent='隱藏'}}if(button.dataset.rotate&&confirm('重建 token 後，重啟 server 並更新對應 agent／套件設定。要繼續嗎？')){await api('/api/rotate',{which:button.dataset.rotate});await refresh();note('新 token 已儲存，重啟後生效。連線設定目前仍顯示執行中的 token。')}if(button.id==='refresh')await refresh()}catch(error){note(error.message)}});
$('settings').addEventListener('submit',async event=>{event.preventDefault();const values={...state.settings};for(const key of Object.keys(values)){if($(key).disabled)continue;values[key]=key==='lanEnabled'?$(key).checked:key==='extensionIds'?$(key).value.split(',').map(v=>v.trim()).filter(Boolean):Number($(key).value)}try{await api('/api/settings',values);await refresh();note('設定已儲存。請在終端機重新啟動 server 後生效。')}catch(error){note(error.message)}});
refresh(true).catch(error=>note(error.message));setInterval(()=>refresh().catch(error=>note(error.message)),5000);`;
